spring.application.name=bookstore_db

# Thông tin kết nối MySQL (Lưu ý cổng 3306 hoặc 3307 tùy theo bước trước ông chọn)
spring.datasource.url=jdbc:mysql://localhost:3307/bookstore?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# Cấu hình Hibernate (Tự động tạo bảng từ code Java)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cổng chạy ứng dụng Spring Boot
server.port=8081

# Cấu hình Mail Server (Mailhog)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# ==========================================
# MOMO PAYMENT GATEWAY (SANDBOX)
# ==========================================
momo.partner-code=MOMOBKUN20180529
momo.access-key=klm05TvNBzhg7h7j
momo.secret-key=at67qH6mk8w5Y1nAyMoYKMWACiEi2bsa
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
# ⚠ Đổi thành IP máy tính trong mạng WiFi (điện thoại và máy tính phải cùng mạng)
momo.redirect-base-url=http://192.168.1.4:8081

